### ISSUE TITLE
Red code error in upgrade Pan

### ISSUE THREAD

**Issue by BlackRosePetals** [Annosz/UIInfoSuite#591]
### Mod Version

2.3.4

### Multiplayer

Single Player

### Visual Settings

100%

### Description

[UI Info Suite 2] This mod failed in the Display.RenderingHud event. Technical details:
NullReferenceException: Object reference not set to an instance of an object.
   at UIInfoSuite2.UIElements.ShowToolUpgradeStatus.OnRenderingHud(Object sender, RenderingHudEventArgs e) in C:\Users\Drew\RiderProjects\DH-UIInfoSuite2\UIInfoSuite2\UIElements\ShowToolUpgradeStatus.cs:line 122
   at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in SMAPI\Framework\Events\ManagedEvent.cs:line 101
[UI Info Suite 2] This mod failed in the Display.RenderedHud event. Technical details:
NullReferenceException: Object reference not set to an instance of an object.
   at UIInfoSuite2.UIElements.ShowToolUpgradeStatus.OnRenderedHud(Object sender, RenderedHudEventArgs e) in C:\Users\Drew\RiderProjects\DH-UIInfoSuite2\UIInfoSuite2\UIElements\ShowToolUpgradeStatus.cs:line 131
   at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in SMAPI\Framework\Events\ManagedEvent.cs:line 101

Smapi Keep repeating these error codes.

**Comment by LizardOnTheInternet** [comment]
I can confirm this for iridium pan in multiplayer as host. The icon does not show and this error shows up:

```
[UI Info Suite 2] This mod failed in the Display.RenderedHud event. Technical details:
NullReferenceException: Object reference not set to an instance of an object.
   at UIInfoSuite2.UIElements.ShowToolUpgradeStatus.OnRenderedHud(Object sender, RenderedHudEventArgs e) in C:\Users\Drew\RiderProjects\DH-UIInfoSuite2\UIInfoSuite2\UIElements\ShowToolUpgradeStatus.cs:line 131
   at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in SMAPI\Framework\Events\ManagedEvent.cs:line 101
```

**Comment by Rogue-Toast** [comment]
There's a debug build in https://github.com/Annosz/UIInfoSuite2/issues/560#issuecomment-2165753026 that corrects this error.
